# --- INFORMATION APPLICATION ---
spring.application.name=vehicule-service
server.port=8081

# --- CONFIGURATION DATABASE (PostgreSQL) ---
# Assure-toi que ton container Postgres est bien lancé sur le port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURATION KAFKA (Broker) ---
# Assure-toi que ton container Kafka est bien lancé sur le port 9092
spring.kafka.bootstrap-servers=localhost:9092

# KAFKA PRODUCER
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# KAFKA CONSUMER
spring.kafka.consumer.group-id=fleet-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- CONFIGURATION KEYCLOAK / OAuth2 Resource Server ---
# JWKS URI utilisée pour valider la signature des tokens JWT Keycloak
# Préféré à issuer-uri pour éviter les échecs au démarrage si Keycloak n'est pas encore up
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:GestionFlotteM1}/protocol/openid-connect/certs

# --- CONFIGURATION GRAPHQL ---
# Point d'entrée de l'API
spring.graphql.path=/graphql
# Interface visuelle GraphiQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# Pour afficher les requêtes SQL générées par GraphQL
spring.graphql.show-sql=true

# --- CORRECTIF POUR L'ERREUR "LOADING" (CORS) ---
# Autorise l'interface GraphiQL à communiquer avec le serveur
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS

# --- CONFIGURATION OBSERVABILITÉ (OpenTelemetry) ---

# Activation des endpoints Actuator pour les métriques et traces
management.endpoints.web.exposure.include=health,metrics,prometheus,info,otlp

# Endpoint pour envoyer les traces vers Jaeger ou le Collector OTel
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# Échantillonnage : 1.0 = 100% des requêtes sont tracées (parfait pour le développement)
management.tracing.sampling.probability=1.0

# Format du log pour inclure TraceID et SpanID (indispensable pour corréler Logs et Traces)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]