global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vehicle-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['vehicle-service:8081']

  - job_name: 'conductor-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['conductor-service:9464']

  - job_name: 'maintenance-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['maintenance-service:9464']

  - job_name: 'localization-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localization-service:9464']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:9464']
