replicaCount: 2

image:
  pullPolicy: Always

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 1000m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: fleet.example.com
  tls:
    enabled: true
    secretName: fleet-tls-secret
