apiVersion: v1
kind: Service
metadata:
  name: fleet-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
    app: fleet-frontend
spec:
  selector:
    app: fleet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.fleetFrontend.port }}
  type: ClusterIP
