apiVersion: v1
kind: Service
metadata:
  name: conductor-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
    app: conductor-service
spec:
  selector:
    app: conductor-service
  ports:
    - protocol: TCP
      port: {{ .Values.conductorService.port }}
      targetPort: {{ .Values.conductorService.port }}
  type: ClusterIP
