apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-service-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.brokers }}"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "{{ .Values.jaeger.endpoint }}"
  KEYCLOAK_URL: "{{ .Values.keycloak.url }}"
  KEYCLOAK_REALM: "{{ .Values.keycloak.realm }}"
