apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
    app: vehicle-service
spec:
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: {{ .Values.vehicleService.port }}
      targetPort: {{ .Values.vehicleService.port }}
  type: ClusterIP
