name: CI-CD Fleet Management

on:
  push:
    branches: [ "main" ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Message de test
        run: echo "Le pipeline fonctionne ! En attente du code Java..."

      - name: Test Connexion Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}